spring.application.name=springSecurityExample

spring.security.user.name=jana
spring.security.user.password=janada


spring.datasource.url=jdbc:mysql://localhost:3306/jwttelu
spring.datasource.username=root
spring.datasource.password=root

