spring.application.name=jwt-demo

spring.data.mongodb.uri=mongodb+srv://janadajayathilaka123:j05F09h8Hl532RCZ@cluster0.hyp74ny.mongodb.net/jwtdemo?retryWrites=true&w=majority

spring.data.mongodb.auto-index-creation=false

